# .github/workflows/static-site.yml
name: Generate Static Site
on:
  push:
    branches: [ main ]
    paths: [ 'app/public/wp-content/uploads/simply-static/temp-files/**' ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy to GitHub Pages
        run: |
          rsync -r app/public/wp-content/uploads/simply-static/temp-files/simply-static-*/* ./docs/
